### ISSUE TITLE
"Gerelateerd pand" variable in verblijfsobjecten seems missing

### ISSUE THREAD

**Issue by mtennekes** [djvanderlaan/bagger#1]
First of all, awesome job! I managed to convert the BAG to csv files within minutes.

I want to match the verblijfsobjecten with the buildings. There does not seem to be a matching key. I was expecting a building-id variable in the verblijfsobjecten.csv.

According to https://bagviewer.kadaster.nl such variable exists:

![capture](https://cloud.githubusercontent.com/assets/2444081/23303718/fb02477e-fa95-11e6-95a4-cc554318ce5a.PNG)

It is called "Gerelateerd pand". Do you know why this isn't included?

**Comment by djvanderlaan** [comment]
Hi Martijn,
I expected that the `hoofdadres` field would link to the buildings, but when testing that wasn't the case. That's why the field description has a question mark. It could be that I missed a field from the verblijfsobjecten file. I'll check tonight.

**Comment by djvanderlaan** [comment]
Martijn,
I had indeed missed a variable in the output. This should be fixed now. However, didn't have time to check if the variable matches those in `panden.csv`.
